src/GrapQLAdmin/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GrapQLAdmin.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/GrapQLAdmin/Pages/Index.cshtml.cs
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Text.Json.Serialization;
using GraphQL.Client.Http;
using GraphQL.Client.Serializer.Newtonsoft;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;

namespace GrapQLAdmin.Pages;


public class AuthorizationConfig
{
    public List<AuthorizationRule> Authorization { get; set; }
}

public class AuthorizationRule
{
    public string Name { get; set; }

    public bool Value { get; set; }
}

public class Schema
{
    [JsonPropertyName("data")]
    public Data Data { get; set; }
}

public class Data
{
    [JsonPropertyName("__schema")]
    public SchemaDetails SchemaDetails { get; set; }
}

public class SchemaDetails
{
    [JsonPropertyName("queryType")]
    public QueryType QueryType { get; set; }

    [JsonPropertyName("mutationType")]
    public MutationType MutationType { get; set; }

    [JsonPropertyName("subscriptionType")]
    public SubscriptionType SubscriptionType { get; set; }

    [JsonPropertyName("types")]
    public List<TypeElement> Types { get; set; }

    [JsonPropertyName("directives")]
    public List<Directive> Directives { get; set; }
}

public class QueryType
{
    [JsonPropertyName("name")]
    public string Name { get; set; }
}

public class MutationType
{
    // Add properties if mutation type has any unique identifiers or structures
}

public class SubscriptionType
{
    // Add properties if subscription type has any unique identifiers or structures
}

public class TypeElement
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("fields")]
    public List<Field> Fields { get; set; }

    [JsonPropertyName("inputFields")]
    public List<Field> InputFields { get; set; }

    
    // Include other properties such as inputFields, interfaces, etc., depending on your JSON structure
}

public class Field
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("args")]
    public List<Argument> Args { get; set; }

    [JsonPropertyName("type")]
    public FieldType Type { get; set; }

    [JsonPropertyName("isDeprecated")]
    public bool IsDeprecated { get; set; }

    [JsonPropertyName("deprecationReason")]
    public string DeprecationReason { get; set; }

    public bool IsSelected { get; set; }

}

public class Argument
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("type")]
    public object Type { get; set; }

    [JsonPropertyName("defaultValue")]
    public string DefaultValue { get; set; }
}

public class FieldType
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("ofType")]
    public TypeOfType OfType { get; set; }
}

public class TypeOfType
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }
    // Add more properties as needed
}

public class Directive
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("locations")]
    public List<string> Locations { get; set; }

    [JsonPropertyName("args")]
    public List<Argument> Args { get; set; }
}


public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    public string Message { get; set; }
    private readonly GraphQLHttpClient _client;
    string endpointUrl = "";
    string filePath = ""; // Specify the path to your JSON file

    string introspectionQuery = @"
    query IntrospectionQuery {
        __schema {
            queryType { name }
            mutationType { name }
            subscriptionType { name }
            types {
                kind
                name
                description
                fields(includeDeprecated: true) {
                    name
                    description
                    args {
                        name
                        description
                        type {
                            name
                            kind
                            ofType {
                                name
                                kind
                            }
                        }
                        defaultValue
                    }
                    type {
                        kind
                        name
                        ofType {
                            name
                            kind
                            ofType {
                                name
                                kind
                                ofType {
                                    name
                                    kind
                                    ofType {
                                        name
                                        kind
                                    }
                                }
                            }
                        }
                    }
                    isDeprecated
                    deprecationReason
                }
                inputFields {
                    name
                    description
                    type {
                        name
                        kind
                        ofType {
                            name
                            kind
                        }
                    }
                    defaultValue
                }
                interfaces {
                    name
                    kind
                    ofType {
                        name
                        kind
                    }
                }
                enumValues(includeDeprecated: true) {
                    name
                    description
                    isDeprecated
                    deprecationReason
                }
                possibleTypes {
                    name
                    kind
                    ofType {
                        name
                        kind
                    }
                }
            }
            directives {
                name
                description
                locations
                args {
                    name
                    description
                    type {
                        name
                        kind
                        ofType {
                            name
                            kind
                        }
                    }
                    defaultValue
                }
            }
        }
    }";

    [BindProperty]
    public List<string> SelectedFields { get; set; } // To hold the selected checkboxes
    [BindProperty]
    public string Role { get; set; }

    public bool ConfigFileSet { get; set; }
    [BindProperty]
    public int SelectedUser { get; set; }

    // private readonly IConfiguration _hostingEnvironment;

    public IndexModel(ILogger<IndexModel> logger, IConfiguration configuration)
    {
        _logger = logger;
        filePath = configuration.GetValue<string>("SettingPath");
        endpointUrl = configuration.GetValue<string>("GraphQLUrl");
        SelectedUser = 1;
        var httpClientHandler = new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true
        };

        var httpClient = new HttpClient(httpClientHandler);

        _client = new GraphQLHttpClient(endpointUrl, 
            new NewtonsoftJsonSerializer(), httpClient);

    }

    public void OnGet()
    {

    }


    
    public SchemaDetails Schema { get; set; }
    public bool SchemaAvailable { get; set; }
    
    public void OnPostClearSetting()
    {
        Schema = null;
        System.IO.File.Delete(filePath);
    }
    
    public void OnPostLoadSchema()
    {
        string sch = FetchSchemaAsync(true);
        Schema = System.Text.Json.JsonSerializer.Deserialize<SchemaDetails>(sch);

        if(!System.IO.File.Exists(filePath))
        {
            ConfigFileSet = false;
            return;
        }
        string jsonString = System.IO.File.ReadAllText(filePath);

        AuthorizationConfig setting = System.Text.Json.JsonSerializer.Deserialize<AuthorizationConfig>(jsonString);
        ConfigFileSet = true;
        if (setting == null || setting.Authorization.Count == 0)
        {
            foreach (var type in Schema.Types)
            {
                
                if ((type.Kind == "OBJECT" || type.Kind == "INPUT_OBJECT") && (type.Name == "Query" || type.Name == "AccidentInfo" || type.Name == "AccidentParty" || type.Name == "AccidentsInput" || type.Name == "QuoteResponse"))
                {
                    if (type.Kind == "INPUT_OBJECT")
                    {
                        foreach (var field in type.InputFields  )
                        {
                            field.IsSelected = true;
                        }
                    }
                    else
                    {
                        foreach (var field in type.Fields)
                        {
                            field.IsSelected = true;
                        }
                    }
                }
            }

            return;
        }
       // dynamic expando = new ExpandoObject();
       // expando = Schema;

        foreach (var type in Schema.Types)
        {
            

src/GrapQLAdmin/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GrapQLAdmin.Pages;
public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

src/GrapQLAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-left">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <form method="post" asp-page-handler="LoadSchema" style="display: flex; justify-content: space-between; align-items: center;">
        <h2>GraphQL Schema Introspection</h2>
        <button type="submit">Load Schema</button>
        <button type="submit" asp-page-handler="ClearSetting">Clear Setting</button>
    </form>
    @if (Model.Schema != null)
    {
        <form method="post" asp-page-handler="SaveSchema" style="display: flex; flex-direction: column;">
            @foreach (var type in Model.Schema.Types)
            {
                if ((type.Kind == "OBJECT") && (type.Name == "Query" || type.Name == "AccidentInfo" || type.Name == "AccidentParty" || type.Name == "QuoteResponse"))
                {
                    <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px;">
                        <div>
                            <h3>@type.Name</h3>
                           
                            @foreach (var field in type.Fields)
                            {
                                if (Model.ConfigFileSet == false)
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" value="@type.Name.@field.Name">
                                    <label for="@field.Name">@field.Name</label>
                                }
                                else if(Model.ConfigFileSet == true && !field.IsSelected)
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" disabled value="@type.Name.@field.Name" >
                                    <label for="@field.Name">@field.Name</label>

                                }
                                else
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" value="@type.Name.@field.Name">
                                    
                                    <label for="@field.Name" style="color:green">@field.Name</label>
                                }
                              
                            <br />
                            }
                        </div>
                        <div style="padding-left: 20px;">
                            <select id="selecteduser">
                                <option value="1">Admin</option>
                                <option value="3">IC 1</option>
                                <option value="4">IC 2</option>
                            </select>
                            <input type="checkbox" id="role" name="role" value="admin">  <label for="role">Admin</label>
                            <button type="submit" asp-page-handler="SaveAuthorizationSettings">Save Authorization setting</button>
                            <button type="submit" asp-page-handler="GenerateToken">Generate Token</button>
                        </div>
                    </div>
                }
                else if ((type.Kind == "INPUT_OBJECT") && (type.Name == "AccidentsInput"))
                {
                    <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px;">
                        <div>
                            <h3>@type.Name</h3>

                            @foreach (var field in type.InputFields)
                            {
                                if (Model.ConfigFileSet == false)
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" value="@type.Name.@field.Name">
                                    <label for="@field.Name">@field.Name</label>
                                }
                                else if (Model.ConfigFileSet == true && !field.IsSelected)
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" disabled value="@type.Name.@field.Name">
                                    <label for="@field.Name">@field.Name</label>

                                }
                                else
                                {
                                    <input type="checkbox" id="@field.Name" name="selectedFields" value="@type.Name.@field.Name">

                                    <label for="@field.Name" style="color:green">@field.Name</label>
                                }

                                <br />
                            }
                        </div>
                        <div style="padding-left: 20px;">
                            <select id="selecteduser">
                                <option value="1">Admin</option>
                                <option value="3">IC 1</option>
                                <option value="4">IC 2</option>
                            </select>
                            <input type="checkbox" id="role" name="role" value="admin">  <label for="role">Admin</label>
                            <button type="submit" asp-page-handler="SaveAuthorizationSettings">Save Authorization setting</button>
                            <button type="submit" asp-page-handler="GenerateToken">Generate Token</button>
                        </div>
                    </div>
                }
            }
        </form>
    }

    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <p>@Model.Message</p>
    }
</div>